'use strict';

/**
 * imposition-service — org-level electron-store CRUD + save-time
 * validation for paper sizes and imposition templates (M3 of
 * docs/pdf-imposition-investigation.md). Same shape as routing-service:
 * one dedicated store, one module owning both the data and the guards
 * that keep it internally consistent.
 *
 * The validation is the point. Without a working preview or dispatch
 * (M4/M5), the IPC boundary is the ONLY guard against a template that
 * looks fine in the JSON but fails at dispatch (zero-fit) or steals
 * another template's product code silently. Renderer-side validation
 * arrives in M4 and mirrors these rules — the pattern the rest of the
 * app uses.
 *
 * One M1 engine, no reimplementation: the fit check calls the real
 * `computeLayout`. Same discipline as buildDestFolder — a divergent
 * save-time check is worse than no check because it lulls the operator
 * into believing the template is valid when it isn't.
 *
 * Public surface (thin — the IPC layer wraps these):
 *   listPaperSizes()
 *   savePaperSize(input)                    — throws on validation fail
 *   deletePaperSize(id)                     — throws if in use
 *   listTemplates()
 *   saveTemplate(input)                     — throws on validation fail
 *   deleteTemplate(id)
 *
 * Also exported so tests + M4 renderer previews can call the validator
 * directly without a round-trip through the store:
 *   validatePaperSize(input)
 *   validateTemplate(input, { existingTemplates, paperSizes })
 *   normaliseProductCodes(codes)
 *
 * All width/height/gutter/margin/bleed values are in POINTS. The UI
 * converts to/from the paper size's operator-facing unit via M1's
 * inchesToPoints / mmToPoints; the store never speaks anything else.
 */

const Store  = require('electron-store');
const { UNSAFE_CHARS } = require('../../shared/printUtils');
const { computeLayout } = require('../../pdf-pipeline/imposition-layout');

const store = new Store({ name: 'imposition' });

const KEY_PAPER     = 'paperSizes';
const KEY_TEMPLATES = 'impositionTemplates';

// ─── Small predicates (kept local; the rest of the app has similar ones ──
// but importing from a shared numeric-validators module would spread this
// module's footprint into places that don't need it) ────────────────────
const _isPositiveNumber = (v) => Number.isFinite(v) && v > 0;
const _isNonNegNumber   = (v) => Number.isFinite(v) && v >= 0;
const _isNonEmptyString = (v) => typeof v === 'string' && v.trim().length > 0;

// ═════════════════════════════════════════════════════════════════════════
// Paper sizes
// ═════════════════════════════════════════════════════════════════════════

/**
 * Validate a paper-size input. Returns { ok, value?, error? }.
 *
 * Rules (§5, §5.2):
 *   - name non-empty (after trim)
 *   - width/height finite, positive (points)
 *   - unit 'in' or 'mm'
 *
 * The `id` is either preserved (update) or generated by the caller
 * (savePaperSize does the generate step). This validator does not
 * mutate; it returns a normalised value the store can persist.
 */
function validatePaperSize(input) {
  if (!input || typeof input !== 'object') {
    return { ok: false, error: 'Paper size input must be an object.' };
  }
  if (!_isNonEmptyString(input.name)) {
    return { ok: false, error: 'Paper size name is required.' };
  }
  if (!_isPositiveNumber(input.width)) {
    return { ok: false, error: `Paper size width must be a positive number in points (got ${input.width}).` };
  }
  if (!_isPositiveNumber(input.height)) {
    return { ok: false, error: `Paper size height must be a positive number in points (got ${input.height}).` };
  }
  if (input.unit !== 'in' && input.unit !== 'mm') {
    return { ok: false, error: `Paper size unit must be 'in' or 'mm' (got ${JSON.stringify(input.unit)}).` };
  }
  return {
    ok: true,
    value: {
      id:     input.id,           // may be undefined; caller assigns on new
      name:   input.name.trim(),
      width:  input.width,
      height: input.height,
      unit:   input.unit,
    },
  };
}

function listPaperSizes() {
  return store.get(KEY_PAPER, []);
}

function savePaperSize(input) {
  const check = validatePaperSize(input);
  if (!check.ok) throw new Error(check.error);
  const value = check.value;

  const existing = listPaperSizes();
  if (value.id) {
    const idx = existing.findIndex(p => p.id === value.id);
    if (idx >= 0) {
      existing[idx] = value;
    } else {
      existing.push(value);
    }
  } else {
    // Generator kept simple — routing-service uses the same monotonic
    // timestamp-based ID scheme in the renderer (jobId patterns) and
    // it has served the app fine so far. If two saves race in the
    // same millisecond, the second overwrites the first's ID slot,
    // which is not a data-safety problem here (paper sizes are saved
    // one at a time from a modal).
    value.id = `ps_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
    existing.push(value);
  }
  store.set(KEY_PAPER, existing);
  return value;
}

function deletePaperSize(id) {
  const existing = listPaperSizes();
  const target = existing.find(p => p.id === id);

  // Guard: any template referencing this paperSizeId must be renamed
  // or deleted first. The message names the templates so the operator
  // knows exactly what to fix — hunting for references by hand across
  // dozens of templates is the sort of chore that guards exist to
  // eliminate.
  const templates = listTemplates();
  const referencing = templates.filter(t => t.paperSizeId === id);
  if (referencing.length > 0) {
    const names = referencing.map(t => `'${t.name}'`).join(', ');
    const targetName = target ? `'${target.name}'` : `(id ${id})`;
    throw new Error(
      `Paper size ${targetName} cannot be deleted — used by template(s): ${names}. ` +
      `Delete or reassign those templates first.`
    );
  }

  store.set(KEY_PAPER, existing.filter(p => p.id !== id));
}

// ═════════════════════════════════════════════════════════════════════════
// Imposition templates
// ═════════════════════════════════════════════════════════════════════════

/**
 * Trim, drop empties, and case-insensitively deduplicate a productCodes
 * array. First occurrence wins for casing, so an operator who typed
 * "ABC, abc" gets ['ABC']. Never emits an empty string.
 */
function normaliseProductCodes(codes) {
  if (!Array.isArray(codes)) return [];
  const seen = new Set();
  const out = [];
  for (const raw of codes) {
    if (typeof raw !== 'string') continue;
    const trimmed = raw.trim();
    if (!trimmed) continue;
    const key = trimmed.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(trimmed);
  }
  return out;
}

/**
 * Validate a template input. Returns { ok, value?, error? }.
 *
 * Requires `existingTemplates` and `paperSizes` for cross-references —
 * saveTemplate provides them; callers using validateTemplate directly
 * (M4 preview) must fetch them themselves.
 *
 * Rules per §5.2 + the M3 spec:
 *   - name non-empty
 *   - paperSizeId exists in paperSizes
 *   - gutter, margins.*, artworkBleed all non-negative numbers
 *   - mode 'simplex' | 'duplex'; duplex requires duplexFlipEdge long|short
 *   - gutter ≥ 2 × artworkBleed when artworkBleed > 0
 *   - expectedArtwork {width, height} required, both positive
 *   - REAL M1 fit check: computeLayout must not throw with the template's
 *     inputs. This is what makes save-time validation truthful — same
 *     rule as buildDestFolder (one engine, no reimplementation)
 *   - productCodes trimmed + case-insensitively deduped; a code claimed
 *     by another template rejects the save naming BOTH templates
 *   - outputSubfolder optional; if present, no path separators; other
 *     unsafe chars stripped via the shared UNSAFE_CHARS export
 */
function validateTemplate(input, { existingTemplates = [], paperSizes = [] } = {}) {
  if (!input || typeof input !== 'object') {
    return { ok: false, error: 'Template input must be an object.' };
  }
  if (!_isNonEmptyString(input.name)) {
    return { ok: false, error: 'Template name is required.' };
  }
  if (!_isNonEmptyString(input.paperSizeId)) {
    return { ok: false, error: 'Template paperSizeId is required.' };
  }
  const paperSize = paperSizes.find(p => p.id === input.paperSizeId);
  if (!paperSize) {
    return { ok: false, error: `Template paperSizeId does not exist (got ${JSON.stringify(input.paperSizeId)}).` };
  }

  // Numeric fields — accept undefined/missing for margins edges as 0.
  const margins = {
    top:    (input.margins && input.margins.top    !== undefined) ? input.margins.top    : 0,
    right:  (input.margins && input.margins.right  !== undefined) ? input.margins.right  : 0,
    bottom: (input.margins && input.margins.bottom !== undefined) ? input.margins.bottom : 0,
    left:   (input.margins && input.margins.left   !== undefined) ? input.margins.left   : 0,
  };
  for (const edge of ['top', 'right', 'bottom', 'left']) {
    if (!_isNonNegNumber(margins[edge])) {
      return { ok: false, error: `Template margins.${edge} must be a non-negative number in points (got ${margins[edge]}).` };
    }
  }

  const gutter = (input.gutter === undefined) ? 0 : input.gutter;
  if (!_isNonNegNumber(gutter)) {
    return { ok: false, error: `Template gutter must be a non-negative number in points (got ${gutter}).` };
  }

  const artworkBleed = (input.artworkBleed === undefined) ? 0 : input.artworkBleed;
  if (!_isNonNegNumber(artworkBleed)) {
    return { ok: false, error: `Template artworkBleed must be a non-negative number in points (got ${artworkBleed}).` };
  }

  // Gutter must clear 2 × bleed, else neighbouring bleeds overlap and the
  // finished cards carry pieces of the next card's ink.
  if (artworkBleed > 0 && gutter < 2 * artworkBleed) {
    return {
      ok: false,
      error:
        `Template gutter (${gutter} pt) must be at least 2× artworkBleed ` +
        `(${artworkBleed} pt → ${2 * artworkBleed} pt) — otherwise neighbouring ` +
        `bleeds would overlap. Increase the gutter or reduce the bleed.`,
    };
  }

  // Mode + duplex flip edge
  if (input.mode !== 'simplex' && input.mode !== 'duplex') {
    return { ok: false, error: `Template mode must be 'simplex' or 'duplex' (got ${JSON.stringify(input.mode)}).` };
  }
  if (input.mode === 'duplex' && input.duplexFlipEdge !== 'long' && input.duplexFlipEdge !== 'short') {
    return {
      ok: false,
      error: `Template duplex mode requires duplexFlipEdge 'long' or 'short' (got ${JSON.stringify(input.duplexFlipEdge)}).`,
    };
  }

  // expectedArtwork — REQUIRED per §5.1
  if (!input.expectedArtwork || typeof input.expectedArtwork !== 'object') {
    return { ok: false, error: 'Template expectedArtwork { width, height } is required (§5.1).' };
  }
  if (!_isPositiveNumber(input.expectedArtwork.width)) {
    return { ok: false, error: `Template expectedArtwork.width must be a positive number in points (got ${input.expectedArtwork.width}).` };
  }
  if (!_isPositiveNumber(input.expectedArtwork.height)) {
    return { ok: false, error: `Template expectedArtwork.height must be a positive number in points (got ${input.expectedArtwork.height}).` };
  }

  // Real M1 engine — this is what makes the fit check truthful. Do NOT
  // reimplement (§5.2); the engine's own error message is what surfaces
  // to the operator.
  try {
    computeLayout({
      sheetWidth:     paperSize.width,
      sheetHeight:    paperSize.height,
      margins,
      gutter,
      cellWidth:      input.expectedArtwork.width,
      cellHeight:     input.expectedArtwork.height,
      autoRotate:     !!input.autoRotate,
      mode:           input.mode,
      duplexFlipEdge: input.duplexFlipEdge,
    });
  } catch (err) {
    return { ok: false, error: `Template does not fit paper size: ${err.message}` };
  }

  // Product codes — trim, dedupe, then cross-check against other
  // templates. Case-insensitive throughout: 'ABC' collides with 'abc'.
  const codes = normaliseProductCodes(input.productCodes);
  const codesLower = new Set(codes.map(c => c.toLowerCase()));
  for (const other of existingTemplates) {
    if (other.id === input.id) continue; // updating self, don't collide with self
    const otherCodes = Array.isArray(other.productCodes) ? other.productCodes : [];
    for (const oc of otherCodes) {
      if (typeof oc !== 'string') continue;
      if (codesLower.has(oc.trim().toLowerCase())) {
        return {
          ok: false,
          error:
            `Product code '${oc}' is already assigned to template '${other.name}' ` +
            `(id: ${other.id}). A product code may belong to only one template.`,
        };
      }
    }
  }

  // outputSubfolder — optional; a single folder name, never a path
  // (§7.4 pass-through location).
  let outputSubfolder = '';
  if (input.outputSubfolder !== undefined && input.outputSubfolder !== null) {
    if (typeof input.outputSubfolder !== 'string') {
      return { ok: false, error: `Template outputSubfolder must be a string (got ${typeof input.outputSubfolder}).` };
    }
    const raw = input.outputSubfolder;
    if (raw.includes('/') || raw.includes('\\')) {
      return {
        ok: false,
        error: `Template outputSubfolder must be a single folder name, not a path (got ${JSON.stringify(raw)}).`,
      };
    }
    // Strip everything else that would fail on Win32 or SMB — same
    // safety net folder-copy-filename uses.
    outputSubfolder = raw.replace(UNSAFE_CHARS, '').trim();
  }

  return {
    ok: true,
    value: {
      id:              input.id,
      name:            input.name.trim(),
      paperSizeId:     input.paperSizeId,
      gutter,
      margins,
      expectedArtwork: {
        width:  input.expectedArtwork.width,
        height: input.expectedArtwork.height,
      },
      autoRotate:      !!input.autoRotate,
      artworkBleed,
      cropMarks:       !!input.cropMarks,
      mode:            input.mode,
      duplexFlipEdge:  input.mode === 'duplex' ? input.duplexFlipEdge : null,
      productCodes:    codes,
      outputSubfolder,
    },
  };
}

function listTemplates() {
  return store.get(KEY_TEMPLATES, []);
}

/**
 * Find the imposition template whose productCodes claims the given job
 * product code. Case-insensitive, trim-tolerant — same normalisation the
 * cross-template collision check uses, so a code that dispatch matches
 * against a template is the SAME code save-time validation would have
 * rejected as colliding with another template. Returns null when no
 * template claims the code.
 *
 * Kept in this module so M5 dispatch and any future preview / lookup
 * flow all go through the ONE rule (§5.2 one-code-one-template).
 */
function findTemplateForProductCode(productCode) {
  if (typeof productCode !== 'string') return null;
  const target = productCode.trim().toLowerCase();
  if (!target) return null;
  const templates = listTemplates();
  for (const t of templates) {
    if (!Array.isArray(t.productCodes)) continue;
    for (const c of t.productCodes) {
      if (typeof c !== 'string') continue;
      if (c.trim().toLowerCase() === target) return t;
    }
  }
  return null;
}

function saveTemplate(input) {
  const existing   = listTemplates();
  const paperSizes = listPaperSizes();
  const check = validateTemplate(input, { existingTemplates: existing, paperSizes });
  if (!check.ok) throw new Error(check.error);
  const value = check.value;

  if (value.id) {
    const idx = existing.findIndex(t => t.id === value.id);
    if (idx >= 0) {
      existing[idx] = value;
    } else {
      existing.push(value);
    }
  } else {
    value.id = `tpl_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
    existing.push(value);
  }
  store.set(KEY_TEMPLATES, existing);
  return value;
}

function deleteTemplate(id) {
  const existing = listTemplates();
  store.set(KEY_TEMPLATES, existing.filter(t => t.id !== id));
}

module.exports = {
  // Data access
  listPaperSizes,
  savePaperSize,
  deletePaperSize,
  listTemplates,
  saveTemplate,
  deleteTemplate,
  findTemplateForProductCode,
  // Validators (exported for M4 renderer previews + tests)
  validatePaperSize,
  validateTemplate,
  normaliseProductCodes,
  // Store keys — kept as constants so IPC-adjacent code doesn't repeat
  // magic strings. Not part of the public API surface for anything else.
  _KEY_PAPER:     KEY_PAPER,
  _KEY_TEMPLATES: KEY_TEMPLATES,
};
